### ISSUE TITLE
error during evpn_deploy

### ISSUE THREAD

**Issue by thegryfon** [netenglabs/automatic-for-the-people#4]
Hi Dinesh,

Samuel here, when today tried this repo that you mention, i encountered an error during running ansible, on cfg-fw-interfaces task, which after more detail inspection caused by this one https://github.com/netenglabs/automatic-for-the-people/blob/619d588fafee12fe03357f7f911082af9ff335a6/roles/cfg-fw-interfaces/templates/interfaces.j2#L3

the lo.addr i believe should be lo_addr ?

**Comment by ddutt** [comment]
Samuel, you're right. Fixed.
